# .github/workflows/lint.yml

name: Lint # name of the action (displayed in the github interface)

on:
  push:
    branches:
      - main
      - release/*
      - instance/*
  pull_request:
    branches:
      - main
      - release/*
      - instance/*

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs: # list of things to do
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # install yarn
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Node.js dependencies
        run: yarn ci
        working-directory: /home/runner/work/comserver/backend/package-lock.json

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Code Linting
        run: yarn run lint
