# This workflow will do a clean install of node dependencies, cache/restore them, build the source code
# and run tests across different versions of node
# For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backeend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}

          script: |
            cd company/comserver
            git pull https://github.com/Bibashpoudel/comserver.git
            yarn build
            pm2 reload
